apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.config.SECRET_KEY | b64enc | quote }}
  DB_PASSWORD: {{ .Values.config.DB_PASSWORD | b64enc | quote }}
